### ISSUE TITLE
cant connect

### ISSUE THREAD

**Issue by TheDuckBBarbarian** [spdermn02/TouchPortal_Discord_Plugin#15]
im trying to connect it but every time i enter the details for the discord plug in it keeps loading the page then just saying that localhost refuses to connect.

**Comment by BrOrlandi** [comment]
Same for me. It seems that the plugin is not working anymore...

**Comment by spdermn02** [comment]
The plugin is working correctly. If this is your first Touch Portal Plugin, close down Touch Portal using the icon in the system tray and then start it back up. It will require you to do those setup steps again, but it does work. 

I also will have an update hopefully coming this weekend that will change this process slightly and be a little more reliable. So feel free to set it up now, just know when that update is out, it will require a quick reconfiguration.

**Comment by BrOrlandi** [comment]
Hello @spdermn02 the plugin store the credentials but it never pops up on Discord to allow the integration. Could you please check that? The plugin stopped working for me a couple of days ago. I tried several times to configure it again, got the same problem every time.

**Comment by spdermn02** [comment]
Things to double check are that your redirect url is setup properly as http://localhost on the discord developer app
Next would be, close touch portal and discord from the system tray, restart discord
Go to %APPDATA%\TouchPortal\plugins\config and remove tpdiscord.db
Restart Touch Portal
Redo configuration. 


Note this weekend I'm hoping to wrap up my update now that 2.3 is released and will change the way the plugin handles the authorization and settings.

**Comment by BrOrlandi** [comment]
I tried the new version of the Plugin and everything is working now. Great update! Nice work @spdermn02 !!

**Comment by spdermn02** [comment]
thanks
