### ISSUE TITLE
plugin stopped working with the latest update and had issues before... guess it needs an update :/

### ISSUE THREAD

**Issue by somtinkswong** [spdermn02/TouchPortal_Discord_Plugin#16]

**Comment by spdermn02** [comment]
I'm working on an update which will fix some of the issues as well as make it easier to "fix" the connection. I was planning on releasing this weekend but doing stuff with my family took priority so I'm hopeful for a release this week. 

To full reset the configuration, stop the plugin from the TouchPortal settings->plugins, select in the dropdown for The plugin 
Click stop
Go to %APPDATA%\TouchPortal\plugins\config
Delete tpdiscord.db
Go back to touch portal and click start
You should then go through the on boarding process again.

**Comment by somtinkswong** [comment]
THX for fixing the plugin. mute and deafen, my used functions run perfect again. Big thx for your time and work. Got the biggest respect for programmers allowing us comsumer idiots use their work and knowledge for free. Big big thank you <3  Von: Jameson AllenGesendet: Montag, 22. März 2021 05:48An: spdermn02/TouchPortal_Discord_PluginCc: somtinkswong; AuthorBetreff: Re: [spdermn02/TouchPortal_Discord_Plugin] plugin stopped working with the latest update and had issues before... guess it needs an update :/ (#16) I'm working on an update which will fix some of the issues as well as make it easier to "fix" the connection. I was planning on releasing this weekend but doing stuff with my family took priority so I'm hopeful for a release this week.To full reset the configuration, stop the plugin from the TouchPortal settings->plugins, select in the dropdown for The pluginClick stopGo to %APPDATA%\TouchPortal\plugins\configDelete tpdiscord.dbGo back to touch portal and click startYou should then go through the on boarding process again.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
