### ISSUE TITLE
Authorization Asked For every time Touch Portal Starts

### ISSUE THREAD

**Issue by spdermn02** [spdermn02/TouchPortal_Discord_Plugin#20]
As part of my rewrite I pulled out storing the AuthToken that is provided by Discord

Now looking back that wasn't the best option and need to resolve this.

Thinking what i'll do is create a readonly setting that I can use as a password type.

Update to send the setting when we get an auth token back.
if we get an error need to trap it clear it and reauthorize.

**Comment by nattellyhue** [comment]
@spdermn02 First of all, thanks for the amazing plugin. It has been such a handy plugin for me on stream. If it ain't too much to ask, is there any progress made on this specific bug? It is quite annoying for me to constantly have to reauthorize the app everytime I start Discord :(

**Comment by spdermn02** [comment]
Hey thanks for asking. No I haven't been able to work on this yet. Work and family have taken priority for me over the past few weeks. I do plan on looking into this as soon as I can though.

**Comment by geekgarage** [comment]
I see that this plugin is still being worked on, would it be possible to prioritize this?

**Comment by spdermn02** [comment]
It is on my list. I haven't had a ton of time to rewrite some of the code module I use to handle refresh tokens. It currently doesn't support it so I may be able to work on it this holiday week when I'm off work but no promises.

**Comment by maltazar352** [comment]
hello, I can't make the plugin work can you help me

**Comment by spdermn02** [comment]
finally had a minute to look and low and behold they fixed it in the 4.0.1 release of the discord-rpc library I use. WOOT! (and it was easier than I expected it to be which is good) will be released with the 4.1.0 version of the plugin after some testing.
