### ISSUE TITLE
CANT CREATE API

### ISSUE THREAD

**Issue by MikeDelta21** [spdermn02/TouchPortal_Discord_Plugin#21]
Hello guys, i cant create API

I followed alll the step to create but never apears this "After a few seconds, you should get asked to authorize the application you created as a plugin in Discord, click "Authorize". i already stop and resumed plugin, also i deleted and installed again.

**Comment by bunzrok** [comment]
Also have this issue. Tried removing the plugin, restarting TP and Discord, tried creating a new discord application. I follow the steps but do not get an Authorize dialog from Discord.

**Comment by spdermn02** [comment]
> Also have this issue. Tried removing the plugin, restarting TP and Discord, tried creating a new discord application. I follow the steps but do not get an Authorize dialog from Discord. 
> 
> 
> 
> Edit: Was able to get it working - I was using Discord Canary. I installed the normal Discord, restarted TP and i finally got the auth window. 

There actually is a Canary build if you want to continue to use Canary, it is available under the Installers folder.

**Comment by spdermn02** [comment]
> Hello guys, i cant create API
> 
> 
> 
> I followed alll the step to create but never apears this "After a few seconds, you should get asked to authorize the application you created as a plugin in Discord, click "Authorize". i already stop and resumed plugin, also i deleted and installed again.

So you saved the client id and secret into touch portal and clicked save and nothing showed up. Could try editing touch portal from the TP icon in the system tray and then starting it back up. 
If that doesn't work may need to have you turn on "include plug-in logs" checkbox in the Logs section of the PC application, and then send me your log.txt from %APPDATA%\TouchPortal folder for me to review.
