### ISSUE TITLE
The newest installer plug-in does not work.

### ISSUE THREAD

**Issue by godzilla1999** [spdermn02/TouchPortal_Discord_Plugin#28]
The plugin i imported was okay but the plugin connected shows as disconnected as in the pic.
![issue](https://user-images.githubusercontent.com/84227603/118356309-30edf880-b5a7-11eb-8ccf-af2b123da6a1.PNG)
I even ran discord as admin but still didn't work. I even tried the older version of the update and it still did not work. I'm currently confused.

**Comment by spdermn02** [comment]
It could be that you need to set Skip Process watcher to Yes. And then save and then stop /start the plugin. Some systems don't like the process watcher I'm using

**Comment by godzilla1999** [comment]
Yes, I finally got it to work last now before my stream. Plugin works
great!!

**Comment by Patrii19** [comment]
I have the same problem. I've changed it to Yes and it still doesn't work for me. :(
