### ISSUE TITLE
Bug TPdiscord Plugin is disabled

### ISSUE THREAD

**Issue by zeodgamer** [spdermn02/TouchPortal_Discord_Plugin#32]
I have a problem with the TPDiscord Plugin, when I open the touchportal the plugin works properly but after a while (about 5 minutes) it stops working and I have to restart the TPDiscord Plugin, so that it works again but the same thing happens again , any idea how to solve this problem?

**Comment by spdermn02** [comment]
I'm unsure what would be causing this except for Discord shutting down or messing with its connection.  Are you in the most up to date version?
Also can you make sure that `include plugin logs` checked on the Logs section of touch portal. And then do a full close and reopen of touch portal. When it disconnects could you then send me your log.txt in %APPDATA%\TouchPortal (on windows) or Documents/TouchPortal (on Mac)

**Comment by zeodgamer** [comment]
I thank you for the answer, I even uninstalled touch portal and discord and reinstalled it making sure they were the updated versions, also download the plugin again, when I open touch portal and discord the authorization window appears in discord I give it authorization and the plugin works for about 2 minutes afterwards it does not respond it is quite annoying indeed since I had gotten used to it, it is very useful in my transmissions.

**Comment by spdermn02** [comment]
are you able to get me the log.txt file from `%APPDATA%\TouchPortal` when it happens? That would help me possibly diagnose why it is disconnecting

**Comment by zeodgamer** [comment]
I'm sending you the log.txt, today I had a lot of problems with the plugin, sorry for the delay
[log.txt](https://github.com/spdermn02/TouchPortal_Discord_Plugin/files/7248810/log.txt)

**Comment by spdermn02** [comment]
I rarely have issues with the plugin honestly. But could you make sure you are on the latest released version. 

Also if you have yet done thjs, close down both Touch Portal and Discord from system tray, and then start discord, wait for it to be ready and then start up touch portal and approve the connection. 

I'll review the log more tomorrow to see I can see anything more Obvious

**Comment by spdermn02** [comment]
hmm..
i'll have to see if this is still an issue
```
22:02:15.393 - [ERROR] (Plugin Instance) C:\snapshot\TouchPortal_Discord_Plugin\node_modules\find-process\lib\find_process.js:140
22:02:15.394 - [ERROR] (Plugin Instance)                 return row.Name === cond.name || (row.Name.endsWith('.exe') && row.Name.slice(0, -4) === cond.name)
22:02:15.395 - [ERROR] (Plugin Instance)                                                            ^
22:02:15.395 - [ERROR] (Plugin Instance) 
22:02:15.396 - [ERROR] (Plugin Instance) TypeError: Cannot read property 'endsWith' of undefined
22:02:15.396 - [ERROR] (Plugin Instance) Error reading communication: Connection reset
22:02:15.396 - [ERROR] (Plugin Instance)     at C:\snapshot\TouchPortal_Discord_Plugin\node_modules\find-process\lib\find_process.js:140:60
22:02:15.396 - [ERROR] (Plugin Instance) Plugin Connection has been incorrectly closed... 
22:02:15.397 - [ERROR] (Plugin Instance)     at Array.filter (<anonymous>)
22:02:15.397 - [ERROR] (Plugin Instance) Connection has been closed... 
22:02:15.397 - [ERROR] (Plugin Instance)     at ChildProcess.<anonymous> (C:\snapshot\TouchPortal_Discord_Plugin\node_modules\find-process\lib\find_process.js:135:12)
22:02:15.397 - [ERROR] (Plugin Instance)     at ChildProcess.emit (events.js:314:20)
22:02:15.398 - [ERROR] (Plugin Instance)     at maybeClose (internal/child_process.js:1022:16)
22:02:15.398 - [ERROR] (Plugin Instance)     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```

**Comment by spdermn02** [comment]
this is from the npm package I use so will investigate if they have any solutions/corrections for this.

**Comment by spdermn02** [comment]
looks like this was fixed about 1 month ago - will look at pulling this in and building new versions of my plugin.
their pull request for documentation: https://github.com/yibn2008/find-process/issues/40

**Comment by spdermn02** [comment]
sorry for the delayed response on this: https://github.com/spdermn02/TouchPortal_Discord_Plugin/releases/tag/v4.0.5

is the version that shoudl fix the error reported in your log.txt
