### ISSUE TITLE
Push to Talk no longer working

### ISSUE THREAD

**Issue by jfrazierjr** [spdermn02/TouchPortal_Discord_Plugin#41]
For some context, I had been having trouble with my computer(unrelated to discord or touchportal) so I decided to format and reinstall windows.   Prior to this I made a backup of the touch portal settings, including pages and buttons.     Part of the Touch Portal buttons contained one button to toggle Deafen and a second button to change from voice activity to push to talk.

After reinstalling, i could not get the discord plug in working, so I deleted it and reimported as well as repaeted after downloading the newest version of  "TPDiscord-Win.tpp".(to be honest, it's not really clear WHY the installers folder has multiple windows files)  It seemed inconsistent and off and on would not work even after authorization, however at least right this second the deafen button is working.    However, the button for "Discord: Set Voice Type to" no longer seems to do anything.     

To test, I added a NEW button "Discord: Select Channel" and this new button works perfectly fine, so I am at a loss.   Of course, since both the new select channel button works as well as the toggle deafen, the plug it is running and working, so any help would be greatly appreciated.   Note that this is on Windows 10 in case that is important.

**Comment by jfrazierjr** [comment]
Ok, additional information.   I don't know if this will help or hurt, but I reinstalled TP by downloading the latest version from their site(I had last night used the installer from mid last year or so).  Additionally, using some other troubleshooting I opend the TPDiscord folder in APPData/Roaming/TouchPortal/plugins/TPDiscord.    

On a lark, stopped the plug in within TP and clicked on tpdiscord.exe.  This seems to make everything work correctly except for the Push to talk.   I found that each time I select push to talk, I get a stack trace.  I scrolled back up to the initialization and go this:

2022-01-12T01:26:09.658Z : TPDiscord :DEBUG: Action Message received
2022-01-12T01:26:09.658Z : TPDiscord :DEBUG: {"data":[{"id":"discordVoiceMode","value":"Push To Talk"}],"pluginId":"TPDiscord","actionId":"discord_voice_mode_change","type":"action"}
(node:8512) UnhandledPromiseRejectionWarning: Error: child "mode" fails because ["mode" is not allowed]
    at RPCClient._onRpcMessage (C:\snapshot\TouchPortal_Discord_Plugin\node_modules\discord-rpc\src\client.js:185:19)
    at IPCTransport.emit (events.js:314:20)
    at C:\snapshot\TouchPortal_Discord_Plugin\node_modules\discord-rpc\src\transports\ipc.js:138:18
    at decode (C:\snapshot\TouchPortal_Discord_Plugin\node_modules\discord-rpc\src\transports\ipc.js:92:5)
    at Socket.<anonymous> (C:\snapshot\TouchPortal_Discord_Plugin\node_modules\discord-rpc\src\transports\ipc.js:120:7)
    at Socket.emit (events.js:314:20)
    at emitReadable_ (_stream_readable.js:557:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
(node:8512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8512) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Is it possible that the discord API has changed in  recent release (downloaded discord from their site last night)?

**Comment by spdermn02** [comment]
It's did have to correct something in the base library and may have forgotten to do that when rebuilding the latest versions. I'll have a look. Thanks for the info

**Comment by spdermn02** [comment]
I have a fix for this as well as another few items are you able to do a quick test for me as it works on my machine, but want to make sure it works for you

also no more authorization prompt should show up if you had prior authorized the plugin connection to discord!
https://github.com/spdermn02/TouchPortal_Discord_Plugin/blob/discord-rpc-update/Installers/TPDiscord-Win.tpp

**Comment by spdermn02** [comment]
Nevermind - found somebody active on the discord server to test it out.
