### ISSUE TITLE
not opening the developer portal or the aithorize window

### ISSUE THREAD

**Issue by leeuwcraft** [spdermn02/TouchPortal_Discord_Plugin#43]
my plugin is not opening any form of windows with discord and chrome open in the background
any ideas on fixing it?

**Comment by spdermn02** [comment]
Hey, sorry I'm just getting back to you. If this is your first plugin, fully restart touch portal from the system tray touch portal icon. 

If that doesn't correct it, please make sure that `include plug-in logs` is checked on your Logs tab of touch portal, restart and after about 45 seconds please attach a copy of your log.txt from %APPDATA%\TouchPortal for me to review.

**Comment by spdermn02** [comment]
any update @leeuwcraft

**Comment by Elmegaard** [comment]
I had the same issue, did the restart as you suggested and it started working.
