### ISSUE TITLE
Cannot import into Touch Portal 3.0.8.0.0

### ISSUE THREAD

**Issue by gviscardi** [spdermn02/TouchPortal_Discord_Plugin#45]
Whenever I attempt to import this plugin into windows Touch Portal 3.0.8.0.0 it starts importing but then gets stuck at "Analyzing" and doesn't move. I've left it for about an hour and nothing had changed. Other plugins imported just fine. I've tried each of the Windows installers from the repo but they all do the same thing. I've tried on multiple machines also.
Is there something I'm missing?

Windows 10 Pro x64

**Comment by spdermn02** [comment]
Hey, I haven't ever experienced that with the way my plugins are packaged. But I'll do some testing to see if I can figure out if it's reproducible. 

In the end if you want to manually install the plugin, this is just a .zip file with the extension renamed. So just changed .tpp to .zip and then uncompressed it. You can then take that folder and manually put in %APPDATA%\TouchPortal\plugins and restart TP from the system tray. It will then pick up the plugin and attempt to load it.

**Comment by gviscardi** [comment]
Ok, so after your comment, I was going through the files and decided to try the actual release download instead of the cloning the tpp file from the Installers directory.
The release download worked just fine, I must have messed something up when cloning the individual file.
