### ISSUE TITLE
Feature Request - Post to Channel

### ISSUE THREAD

**Issue by Darydactyl** [spdermn02/TouchPortal_Discord_Plugin#5]
Would it be possible to include the ability to post to channels?
i.e. On Twitch, using the Channel Points redemption, I would love to post the suggestions into a private channel on my Discord. Which is currently setup outputting to a txt file (screenshot attached)
![image](https://user-images.githubusercontent.com/70101659/90980609-643db280-e554-11ea-82fc-c3fa465dc183.png)

**Comment by spdermn02** [comment]
Thanks for the request and explanation. The RPC api is deprecated but there are still functions to do stuff like this so I'll investigate to see if it's still possible.

**Comment by spdermn02** [comment]
Did some research - and from the documentation I see, without using a BOT you cannot write messages using the connectivity method I am using.  I'm going to leave this open as I continue to do research but wanted to share that info.

If you are curious, these are the MAX I would have access to https://discord.com/developers/docs/topics/rpc#commands-and-events and only then with the correct permission scope to do so.

**Comment by spdermn02** [comment]
@Darydactyl  - may need to look into a Webhook for your discord server: https://dev.to/oskarcodes/send-automated-discord-messages-through-webhooks-using-javascript-1p01

This could then just post using the https post action in Touch Portal a specifically formatted data object to the webhook. I'll do some testing and let you know how it goes.

**Comment by spdermn02** [comment]
Yeah webhooks - works fantastic. I'll put a video together or something to show it off. But yeah - that is the feature you want.

**Comment by spdermn02** [comment]
I could build this into the discord plugin and grant you the ability to "create" a webhook for your server, etc. and select the channel for it to go into and then just make a list of webhooks by name and give you the option to
```
use "hook" to send "message" to discord
```
where "hook" is a droppdown of available webhooks you have configured, and "message" is whatever message you want to send... hmm let me think about it - i'll reopen this.

**Comment by Darydactyl** [comment]
I have webhooks for other features using IFTTT, this sounds like a great feature to implement

**Comment by marco0904** [comment]
would it be possible to add buttons for push to talk and vad?

**Comment by spdermn02** [comment]
> would it be possible to add buttons for push to talk and vad?

I have this marked as another enhancement that I'm investigating for the next version.

**Comment by spdermn02** [comment]
At this point, webhooks are kind of a pain, and don't really have a great design for this sort of thing, so going to close this request as their api directly doesn't provide any capability to post messages directly.
