### ISSUE TITLE
Sometimes Plugin Needs Restart

### ISSUE THREAD

**Issue by spaz926** [spdermn02/TouchPortal_Discord_Plugin#50]
Sometimes I will have to stop and then start the plugin to get any of my actions working again.

Perhaps adding some kind of intermittent check that TouchPortal is connected to Discord would solve this (every hour maybe)? Or even check the connection when an action is requested.

I'm not able to reliably reproduce the issue. It just happens sporadically.

**Comment by spdermn02** [comment]
I think I need to also change how new channel detection and stuff works as that can screw with at least server/channel level actions. 

If discord messes up its endpoint, I've had it not return any error but nothing works either. Which is even more frustrating. Especially after discord updates I've had issues with that.

**Comment by spdermn02** [comment]
Assuming this is sorted with the 4.3.1 release I made. Let me know if you still have issues.
