### ISSUE TITLE
Authorization does not pop up

### ISSUE THREAD

**Issue by ninjapenugin** [spdermn02/TouchPortal_Discord_Plugin#53]
I have followed all of the instructions to install/set up the plugin for use; however, after step 22, Discord does not have a pop up that asks me to authorize the application. I did open up the tpdiscord.exe application that can be found in the touchportal appdata folder, and when the cmd prompt pops up, it says there is a login error, and the error is that it could not connect. I have deleted the application in the Discord Developer portal, and recreated it, but that still does not work. Any ideas on next steps that I could take to figure out what is wrong, so I can get this fixed?

**Comment by ninjapenugin** [comment]
When looking at the plugin settings, Looking at the Plugin Connected section, it says that it is Disconnected. The plugin is running. I am running version 4201

**Comment by spdermn02** [comment]
I've had issues where discord needs to be fully restarted itself due to the api interface that is used being broken somehow. I suggest full shutdown of touch portal and discord from system tray, start discord after it is up and running start touch portal.

**Comment by ninjapenugin** [comment]
Restarted both, and started in the order recommended: no pop up. After waiting a few minutes, I even tried restarting the plugin via the TP settings, nothing there either.

**Comment by spdermn02** [comment]
Typically that is due to incorrect user who created the client/secret (like if you have multiple discord logins). Or that the redirect url is not `http://localhost` 

But could you click `include plug-in logs` on the Logs tab and then restart touch portal. After a minute send me the log.txt from %APPDATA%\TouchPortal

**Comment by ninjapenugin** [comment]
[log.txt](https://github.com/spdermn02/TouchPortal_Discord_Plugin/files/8500810/log.txt)

**Comment by spdermn02** [comment]
Thanks I'll review today and see if I can determine the issue

**Comment by spdermn02** [comment]
resolved through discord dm

discord was running as Admin mode, so Touch Portal also needed to run as Admin mode in order to have access to the message queue used for the communication to the Discord App.
