### ISSUE TITLE
Discord does not pop up

### ISSUE THREAD

**Issue by majdmfpro** [spdermn02/TouchPortal_Discord_Plugin#61]
I have followed all of the instructions to install/set up the plugin for use; however discord is not poping up to autherize the plugin
[log.txt](https://github.com/spdermn02/TouchPortal_Discord_Plugin/files/9639884/log.txt)
Please Help

**Comment by spdermn02** [comment]
You downloaded the Discord Canary build, my guess is you run the base install of Discord, and need to download TPDiscord-Win.tpp, 

https://github.com/spdermn02/TouchPortal_Discord_Plugin/releases/download/v4.3.1/TPDiscord-Win.tpp

**Comment by majdmfpro** [comment]
I don't know what to say, you are not a normal person, you are a LEGEND, it worked 🤩
thank you.
