### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by MrKillaKareBear** [spdermn02/TouchPortal_Discord_Plugin#69]
Can we get a Streamer Mode Toggle action, just like for Mute and Deafen?

**Comment by spdermn02** [comment]
no option i can find will control that from their API Documentation. But I'll continue to look.

**Comment by spdermn02** [comment]
Nothing seems to be available to be able to modify Streamer Mode - i'll keep this in mind for a future release if they ever add the functionality.
