### ISSUE TITLE
localhost:9403 unreachable

### ISSUE THREAD

**Issue by stefan-west1** [spdermn02/TouchPortal_Discord_Plugin#7]
Initially I get the 2 pages, discord developer and localhost:9403 open up no problems, however once submitting the client id and secret the page becomes unreachable. If I reload the page at all even before submitting anything, it also becomes unreachable.

**Comment by Czompi** [comment]
I have the same problem. 
Did you fixed it? If so, can you share the solution with me?
I'm on (a legal version of) `Windows 10 Pro 20H2`, I use paid version of `ESET` as an antivirus and I have the latest version of Discord (as of now it is `Stable 72044 (886176e) Host 0.0.308`) and the `Touch Portal Discord` plugin is the latest version as well (`3.0.1`).

**Comment by Czompi** [comment]
I think I found the problem (but still it does the same thing even after emptying/deleting the file).
![image](https://user-images.githubusercontent.com/26040786/99865876-0ea59000-2bad-11eb-864a-5c7b738fbf2b.png)
These are the contents of my `TPDiscord.db` file. The first and the last line are the exact same.

**Comment by spdermn02** [comment]
@Czompi full close Touch Portal from the system tray Icon, then delete tpdiscord.db file completely, then reopen and redo configuration.  
with a future update when 2.3 of Touch Portal is released,
