### ISSUE TITLE
Feature request: Soundboard

### ISSUE THREAD

**Issue by RazGhost** [spdermn02/TouchPortal_Discord_Plugin#71]
Hi! Discord now has a new integreted soundboard. Can we get a option to add a button for it in the Touch Portal app? (Sorry for my english, thanks a lot in advance)

**Comment by spdermn02** [comment]
At this point Discord would have to update their api (which is currently technically deprecated but still works). I don't know if they will be adding anything else to it. But I could try to do some reverse engineering and see if there is something would allow that communication. But at this point I doubt they hooked in anything.

**Comment by spdermn02** [comment]
Since the Elgato discord plugin just got released with the Soundboard features. I'm looking into trying to figure out what i need to use.

**Comment by spdermn02** [comment]
Still need to reverse engineer the soundboard calls.

**Comment by spdermn02** [comment]
found the calls - have a release v4.4.0-alpha-4 that contains an action to execute the soundboard actions

**Comment by spdermn02** [comment]
in build changes branch
