### ISSUE TITLE
Control Individual Voice Users Volume

### ISSUE THREAD

**Issue by spdermn02** [spdermn02/TouchPortal_Discord_Plugin#73]
As a Discord User I would like to control the volume of other discord users while using Touch Portal. 

This should allow for dynamic number of users (this can be done but is tricky) so that There is a generic page that could be setup to control voice volume for users.

**Comment by cj2tech** [comment]
don't know if this would help at all with dev of this but saw someone made this for stream decks. https://apps.elgato.com/plugins/cz.danol.discordmixer
and https://discord.com/developers/docs/topics/rpc#setuservoicesettings

**Comment by spdermn02** [comment]
Thanks for sharing I'll have a look!

**Comment by gitagogaming** [comment]
This will be possible in a near future update.. 
You will be able to use actions, onHold and Sliders to control the volume for a user as well as their mute state.. 

![image](https://github.com/user-attachments/assets/928b6c28-8ebc-40bd-af1c-b35e1fe4c97a)
![image](https://github.com/user-attachments/assets/22447589-a6fe-4c8b-83c5-81b846fe592d)

See commit for more info
https://github.com/gitagogaming/TouchPortal_Discord_Plugin/commit/1813a9c965dcd67c597f0cf36111db69c21a7f11
