### ISSUE TITLE
[Feature Request] Mic Events

### ISSUE THREAD

**Issue by andrewcartwright1** [spdermn02/TouchPortal_Discord_Plugin#76]
Hi,

I would like to request a feature for events such as mic muted/mic unmuted, deafened/undeafened

It would be awesome to be able to create a two way button so that it can be used for muting and unmuting / deafening/undeafening

Currently I have this set up with IF's but it does not work if I do it inside of discord.

Many thanks,
Andy

**Comment by spdermn02** [comment]
You can already do this by using Events inside of touch portal. No need for dedicated events just use the `When plug-in value changes` event so you can trigger visual changes even when manually click inside discord itself. 

The example button I have in the readme should show that. If not I'll throw and example here tomorrow.

**Comment by spdermn02** [comment]
Okay forgot I removed the buttons and just created a sample page. You could download and import that page. It will probably be tomorrow before I'm back at my computer to get a snapshot of my button I use.

**Comment by spdermn02** [comment]
Here is how i have my Mic button setup
![image](https://github.com/spdermn02/TouchPortal_Discord_Plugin/assets/4458464/247cc35a-f08e-4564-a8b8-6c5b3819d23b)

and my Deafen button
![image](https://github.com/spdermn02/TouchPortal_Discord_Plugin/assets/4458464/224c8d2a-6bdc-43e0-9be1-4795def958ee)

using the OnEvent tab will allow the visuals to change when changing from discord itself, or within the touch portal app.

**Comment by andrewcartwright1** [comment]
Thanks for this!
