### ISSUE TITLE
Active Speaker Status Feature Request

### ISSUE THREAD

**Issue by ArakoKatoc** [spdermn02/TouchPortal_Discord_Plugin#79]
I'd like for the plugin to be able to read what speaker is currently speaking, in sort of the way Fugi Reactive does, so that I can trigger other actions based on who is currently talking (IE moving active speakers on and off the OBS overlay as they become active.) Maybe I'm just not familiar enough with the plugin yet and this already exists if so I apologize!

**Comment by spdermn02** [comment]
Currently there isn't a state for this. But I'll look into it.

**Comment by ArakoKatoc** [comment]
I would definitely appreciate it, I need a solution that would allow me to control overlays based on the person speaking in discord and I would also like to use videos rather than animated gifs, and Reactive doesn't support that.

**Comment by gitagogaming** [comment]
This is has been added as a feature. 

Example of using it for OBS Studio to activate sources based on the user speaking.. 
can also be done just for the 'last' person speaking so its only one person all the time..
https://github.com/user-attachments/assets/16dcfb80-62d1-4497-90e1-a76696ee393b

here are some of the states you have available for users in the voice chat. 
![image](https://github.com/user-attachments/assets/4d8fb3c4-99ee-462f-9ac3-7a1bbb937bfc)

--
See Commit Details
https://github.com/gitagogaming/TouchPortal_Discord_Plugin/commit/1813a9c965dcd67c597f0cf36111db69c21a7f11
