### ISSUE TITLE
A Request: Please add Butten change on Discord message

### ISSUE THREAD

**Issue by ApophysX** [spdermn02/TouchPortal_Discord_Plugin#80]
Hello,

Is it possible if you receive a message in Discord that this is displayed in the TouchPortal?  1 New message.

**Comment by spdermn02** [comment]
Not that I'm aware of. I tried a permission that in theory should have enabled it. But never got anything to work for it. I'll add it to my list of things to re-investigate after I get the latest release fully complete.

**Comment by gitagogaming** [comment]
This is indeed possible.  I have integrated into a future release once Spdermn gets some time to review everything.  
![image](https://github.com/user-attachments/assets/7f128ff3-4561-46d2-8f88-a0f1b2e239d8)

**Comment by gitagogaming** [comment]
This has been added as an event 

Here is a further example of how to also display the users avatar or open the user's DM

![image](https://github.com/user-attachments/assets/a13b87af-7eab-450e-9292-ca5859ca02d6)


**Commit**
https://github.com/gitagogaming/TouchPortal_Discord_Plugin/commit/f607c813f4de44ab6979cc907d37314105068622
