### ISSUE TITLE
Join in a DC Voice channel

### ISSUE THREAD

**Issue by s4t4n** [spdermn02/TouchPortal_Discord_Plugin#83]
Hey, I tried this two functions:
![grafik](https://github.com/user-attachments/assets/04986383-43b1-4b3e-84da-6d4619c905f1)

With the first one, the serverlist is only sometimes filled, but the channel parameter ist empty ever.

The 2nd function with id, it just do nothing.

What can I do`?

greet

log:
`00:16:11.274 - [ERROR] [Plugin Instance] C:\snapshot\TouchPortal_Discord_Plugin\src\index.js:106
00:16:11.274 - [ERROR] [Plugin Instance]     let guildId = guilds.idx[server];
00:16:11.274 - [ERROR] [Plugin Instance]                             ^
00:16:11.274 - [ERROR] [Plugin Instance] 
00:16:11.274 - [ERROR] [Plugin Instance] TypeError: Cannot read properties of undefined (reading 'Dennis_Gaming')
00:16:11.274 - [ERROR] [Plugin Instance]     at TouchPortalClient.<anonymous> (C:\snapshot\TouchPortal_Discord_Plugin\src\index.js:106:29)
00:16:11.274 - [ERROR] [Plugin Instance]     at TouchPortalClient.emit (node:events:537:28)
00:16:11.274 - [ERROR] [Plugin Instance]     at C:\snapshot\TouchPortal_Discord_Plugin\node_modules\touchportal-api\dist\src\client.js:304:32
00:16:11.274 - [ERROR] [Plugin Instance]     at Array.forEach (<anonymous>)
00:16:11.275 - [ERROR] [Plugin Instance]     at Socket.<anonymous> (C:\snapshot\TouchPortal_Discord_Plugin\node_modules\touchportal-api\dist\src\client.js:267:19)
00:16:11.275 - [ERROR] [Plugin Instance]     at Socket.emit (node:events:537:28)
00:16:11.275 - [ERROR] [Plugin Instance]     at addChunk (node:internal/streams/readable:324:12)
00:16:11.275 - [ERROR] [Plugin Instance]     at readableAddChunk (node:internal/streams/readable:293:11)
00:16:11.275 - [ERROR] [Plugin Instance]     at Readable.push (node:internal/streams/readable:234:10)
00:16:11.275 - [ERROR] [Plugin Instance]     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
00:16:11.275 - [ERROR] [Plugin Instance] 
00:16:11.275 - [ERROR] [Plugin Instance] Node.js v18.5.0
00:16:11.276 - [ERROR] [Plugin Instance] Plugin Connection (1) has been incorrectly closed... `

**Comment by gitagogaming** [comment]
@s4t4n Is this issue still occuring for you? 

If so.. if the 'Dennis_Gaming' server is public.. please send me an invite to it so I can investigate what may be causing the crash

**Comment by spdermn02** [comment]
@s4t4n have you updated to the latest version of the plugin. If not see if that corrects the issue.

**Comment by s4t4n** [comment]
oha sorry,  I had a time no internet.
the v 5.0.0 a4 works fine!.. thank you a lot
