### ISSUE TITLE
nick_summerz@hotmail.com

### ISSUE THREAD

**Issue by nick300170** [spdermn02/TouchPortal_Discord_Plugin#94]
![TP_Issue](https://github.com/user-attachments/assets/b486e44d-2422-4e2d-84db-d7ea54ed19d6)

**Comment by nick300170** [comment]
This the issue i had with TP sending this message

**Comment by nick300170** [comment]
https://www.touch-portal.com/api/index.php?section=communication_create_update_connector_data

This is what the code means

**Comment by spdermn02** [comment]
Luckily this is just a warning and hasn't ever been reported to actually cause Touch Portal issues. But we will review the code and see if we can shore up the cause of it.

**Comment by riquelmehoy** [comment]
**cjhz**

**Comment by riquelmehoy** [comment]
**BGY**
