### ISSUE TITLE
plugin wont work when using discord PTB

### ISSUE THREAD

**Issue by gitagogaming** [spdermn02/TouchPortal_Discord_Plugin#99]
There is an issue right now that if you are using discordPTB or possibly even canary version, the plugin will not properly register itself.. 

A temporary fix for this is to disable the process watcher in the plugin settings and then reboot the plugin.. 
It should connect properly now as long as discord is open first.. 

![image](https://github.com/user-attachments/assets/adc68436-9437-4b2f-b125-7ae8221e5c99)

**Comment by spdermn02** [comment]
Fix committed: https://github.com/spdermn02/TouchPortal_Discord_Plugin/pull/101

**Comment by spdermn02** [comment]
This has been merged and tagged as v5.0.0-alpha-5
